#! /usr/bin/env python3

from setuptools import setup

setup(name="python-zwo",
      version="0.0.1",
      description="ZWO Devices library",
      url="https://github.com/RAA80/python-zwo",
      author="Alexey Ryadno",
      author_email="aryadno@mail.ru",
      license="MIT",
      packages=["zwo", "zwo.libs"],
      package_data={"zwo": ["libs/efw/win32/*.dll",
                            "libs/efw/win64/*.dll",
                            "libs/efw/linux32/*.*",
                            "libs/efw/linux64/*.*"]},
      platforms=["Linux", "Windows"],
      classifiers=["Development Status :: 3 - Alpha",
                   "Intended Audience :: Science/Research",
                   "Intended Audience :: Developers",
                   "License :: OSI Approved :: MIT License",
                   "Operating System :: Microsoft :: Windows",
                   "Operating System :: POSIX :: Linux",
                   "Operating System :: POSIX",
                   "Programming Language :: Python :: 3",
                   "Programming Language :: Python :: 3.9",
                   "Programming Language :: Python :: 3.10",
                   "Programming Language :: Python :: 3.11",
                  ],
     )
